/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI_admin;

import UI_User.*;
import UI_guest.JFrameIndexGuest;
import entities.*;
import dao.*;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author vomin
 */
public class JFrameIndexAdmin extends javax.swing.JFrame {

    private conferenceDAO cfDAO = new conferenceDAO();
    private placeDAO plDAO = new placeDAO();
    private userDAO usDAO = new userDAO();
    SimpleDateFormat newDateFormat = new SimpleDateFormat("yyyy-MM-dd hh:mm:ss");
    private User CurrentUser;
    private attendanceDAO atDAO = new attendanceDAO();
    DefaultTableModel dtm_con = new DefaultTableModel();

    DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd HH:mm:ss");
    LocalDateTime now = LocalDateTime.now();

    /**
     * Creates new form JFrameIndexAdmin
     */
    public JFrameIndexAdmin() {
        initComponents();
        LoadData();
    }

    public JFrameIndexAdmin(User temp) {
        initComponents();
        LoadData();
        this.CurrentUser = temp;
        System.out.println(CurrentUser.getName());
    }

    public void LoadData() {
        //---Data of conference
        dtm_con.addColumn("ID");
        dtm_con.addColumn("Tên");
        dtm_con.addColumn("Thông tin chung");
        dtm_con.addColumn("Thời gian bắt đầu");
        dtm_con.addColumn("Thời gian kết thúc");
        dtm_con.addColumn("Số lượng khách mời");
        dtm_con.addColumn("Chi tiết");
        List<Conference> ls_cf = cfDAO.findAll();
        for (Conference temp : ls_cf) {

            dtm_con.addRow(new Object[]{temp.getIdConference(), temp.getName(), temp.getGeneralInfo(), temp.getStartedtime(), temp.getEndedtime(), temp.getVisitors(), temp.getDetail()});
        }
        this.listConference.setModel(dtm_con);

        DefaultTableModel dtm_visitors = new DefaultTableModel();
        dtm_visitors.addColumn("Tên hội nghị");
        dtm_visitors.addColumn("Username");
        dtm_visitors.addColumn("Tên khách mời");
        dtm_visitors.addColumn("status");
        this.listVisitors.setModel(dtm_visitors);

        List<Place> ls_place = plDAO.findAll();
        String[] data = new String[ls_place.size()];
        for (int i = 0; i < ls_place.size(); i++) {
            data[i] = ls_place.get(i).getName();
        }
        DefaultComboBoxModel cbm = new DefaultComboBoxModel(data);
        this.placeComboBox.setModel(cbm);
    }

    private void filter(String query) {
        TableRowSorter<TableModel> rowSorter = new TableRowSorter<>(dtm_con);
        this.listConference.setRowSorter(rowSorter);

        rowSorter.setRowFilter(RowFilter.regexFilter(query));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        optionSpace = new javax.swing.JPanel();
        showConferenceButton = new javax.swing.JButton();
        avatar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        editButton = new javax.swing.JButton();
        statisticButton = new javax.swing.JButton();
        logoutButton = new javax.swing.JButton();
        playground = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listConference = new javax.swing.JTable();
        addConferenceButton = new javax.swing.JButton();
        addPlaceButton = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        searchBar = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        nameConferenceTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        generalInfoTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        startedTimeTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        endedTimeTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        detailTextArea = new javax.swing.JScrollPane();
        detailTextField = new javax.swing.JTextArea();
        updateButton = new javax.swing.JButton();
        visitorsTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        placeComboBox = new javax.swing.JComboBox<>();
        deleteButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        listVisitors = new javax.swing.JTable();
        confirmButton = new javax.swing.JButton();
        denyButton = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        optionSpace.setBackground(new java.awt.Color(0, 0, 153));

        showConferenceButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        showConferenceButton.setText("DANH SÁCH HỘI NGHỊ");
        showConferenceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showConferenceButtonActionPerformed(evt);
            }
        });

        avatar.setPreferredSize(new java.awt.Dimension(246, 246));

        jLabel1.setText("AVATAR");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setIconTextGap(10);
        jLabel1.setInheritsPopupMenu(false);
        jLabel1.setPreferredSize(new java.awt.Dimension(30, 30));

        editButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        editButton.setForeground(new java.awt.Color(0, 51, 204));
        editButton.setText("Xem, chỉnh sửa thông tin cá nhân");
        editButton.setBorder(null);
        editButton.setContentAreaFilled(false);
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout avatarLayout = new javax.swing.GroupLayout(avatar);
        avatar.setLayout(avatarLayout);
        avatarLayout.setHorizontalGroup(
            avatarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(avatarLayout.createSequentialGroup()
                .addGroup(avatarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(avatarLayout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(avatarLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(editButton)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        avatarLayout.setVerticalGroup(
            avatarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(avatarLayout.createSequentialGroup()
                .addContainerGap(67, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addComponent(editButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        statisticButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        statisticButton.setText("DANH SÁCH NGƯỜI DÙNG");
        statisticButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statisticButtonActionPerformed(evt);
            }
        });

        logoutButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        logoutButton.setText("ĐĂNG XUẤT");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout optionSpaceLayout = new javax.swing.GroupLayout(optionSpace);
        optionSpace.setLayout(optionSpaceLayout);
        optionSpaceLayout.setHorizontalGroup(
            optionSpaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(optionSpaceLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(optionSpaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(showConferenceButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(statisticButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, optionSpaceLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(optionSpaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(avatar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(logoutButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        optionSpaceLayout.setVerticalGroup(
            optionSpaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, optionSpaceLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(avatar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addComponent(showConferenceButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(statisticButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(logoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        playground.setPreferredSize(new java.awt.Dimension(1006, 800));

        jPanel1.setBackground(new java.awt.Color(0, 0, 153));

        listConference.setAutoCreateRowSorter(true);
        listConference.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        listConference.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listConferenceMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listConference);

        addConferenceButton.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        addConferenceButton.setForeground(new java.awt.Color(0, 102, 204));
        addConferenceButton.setText("Thêm hội nghị");
        addConferenceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addConferenceButtonActionPerformed(evt);
            }
        });

        addPlaceButton.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        addPlaceButton.setForeground(new java.awt.Color(0, 102, 204));
        addPlaceButton.setText("Thêm địa điểm");
        addPlaceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPlaceButtonActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Tìm kiếm");

        searchBar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBarActionPerformed(evt);
            }
        });
        searchBar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchBarKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 983, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addPlaceButton)
                .addGap(18, 18, 18)
                .addComponent(addConferenceButton)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(searchBar, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(searchBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addPlaceButton)
                    .addComponent(addConferenceButton))
                .addGap(2, 2, 2))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Infomation of conference", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 2, 18))); // NOI18N
        jPanel2.setForeground(new java.awt.Color(204, 204, 204));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Tên hội nghị");

        nameConferenceTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameConferenceTextFieldActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Thông tin chung:");

        generalInfoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generalInfoTextFieldActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Thời gian bắt đầu:");

        startedTimeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startedTimeTextFieldActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Thời gian kết thúc");

        endedTimeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                endedTimeTextFieldActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Nơi tổ chức:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Chi tiết:");

        detailTextField.setColumns(20);
        detailTextField.setRows(5);
        detailTextArea.setViewportView(detailTextField);

        updateButton.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        updateButton.setForeground(new java.awt.Color(0, 0, 204));
        updateButton.setText("Cập nhật");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        visitorsTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visitorsTextFieldActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Số lượng khách tham gia:");

        placeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        deleteButton.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        deleteButton.setForeground(new java.awt.Color(255, 0, 0));
        deleteButton.setText("Xóa ");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(77, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2)
                    .addComponent(nameConferenceTextField)
                    .addComponent(jLabel3)
                    .addComponent(generalInfoTextField)
                    .addComponent(jLabel4)
                    .addComponent(startedTimeTextField)
                    .addComponent(jLabel5)
                    .addComponent(endedTimeTextField)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(detailTextArea, javax.swing.GroupLayout.DEFAULT_SIZE, 353, Short.MAX_VALUE)
                    .addComponent(visitorsTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 353, Short.MAX_VALUE)
                    .addComponent(jLabel8)
                    .addComponent(placeComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(65, 65, 65))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(updateButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nameConferenceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(generalInfoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(startedTimeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(endedTimeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(placeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(visitorsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(detailTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateButton)
                    .addComponent(deleteButton))
                .addGap(0, 65, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "List of visitors", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 2, 18))); // NOI18N

        listVisitors.setAutoCreateRowSorter(true);
        listVisitors.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        listVisitors.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listVisitorsMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(listVisitors);

        confirmButton.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        confirmButton.setForeground(new java.awt.Color(0, 102, 204));
        confirmButton.setText("Xác nhận");
        confirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmButtonActionPerformed(evt);
            }
        });

        denyButton.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        denyButton.setForeground(new java.awt.Color(255, 0, 0));
        denyButton.setText("Từ chối");
        denyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                denyButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(confirmButton, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(denyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmButton)
                    .addComponent(denyButton))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel9.setText("IMAGE");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout playgroundLayout = new javax.swing.GroupLayout(playground);
        playground.setLayout(playgroundLayout);
        playgroundLayout.setHorizontalGroup(
            playgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(playgroundLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(playgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        playgroundLayout.setVerticalGroup(
            playgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(playgroundLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(playgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(playgroundLayout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(optionSpace, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(playground, javax.swing.GroupLayout.DEFAULT_SIZE, 983, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(playground, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 841, Short.MAX_VALUE)
                    .addComponent(optionSpace, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void showConferenceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showConferenceButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_showConferenceButtonActionPerformed

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        // TODO add your handling code here:
        JFrameAccountAdmin j = new JFrameAccountAdmin(CurrentUser);
        j.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_editButtonActionPerformed

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        // TODO add your handling code here:
        JFrameIndexGuest j = new JFrameIndexGuest();
        j.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void nameConferenceTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameConferenceTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameConferenceTextFieldActionPerformed

    private void generalInfoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generalInfoTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_generalInfoTextFieldActionPerformed

    private void startedTimeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startedTimeTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_startedTimeTextFieldActionPerformed

    private void endedTimeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_endedTimeTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_endedTimeTextFieldActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        // TODO add your handling code here:
        Conference cf = cfDAO.find(Integer.parseInt(this.listConference.getValueAt(this.listConference.getSelectedRow(), 0).toString()));
        Place chosen = plDAO.find(placeComboBox.getSelectedIndex() + 1);
        if (!checkAddConference(cf, chosen, this.startedTimeTextField.getText(), this.endedTimeTextField.getText())) {
            JOptionPane.showMessageDialog(null, "Cập nhật nghị không thành công !!! Thời gian đó có sk đang diễn ra");
            return;
        }

        if (Integer.parseInt(this.visitorsTextField.getText()) > chosen.getCapacity()) {
            JOptionPane.showMessageDialog(null, "Nơi tổ chức không đủ sức chứa !!!");
            return;
        }

        cf.setName(nameConferenceTextField.getText());
        cf.setGeneralInfo(generalInfoTextField.getText());
        try {
            cf.setStartedtime(newDateFormat.parse(startedTimeTextField.getText()));
            cf.setEndedtime(newDateFormat.parse(endedTimeTextField.getText()));
        } catch (Exception e) {
            e.printStackTrace();
        }

        cf.setPlace(chosen);
        cf.setVisitors(Integer.parseInt(visitorsTextField.getText()));
        cf.setDetail(detailTextField.getText());
        if (cfDAO.update(cf)) {
            JOptionPane.showMessageDialog(null, "Cập nhật hội nghị thành công !!!");
            DefaultTableModel dtm_con = new DefaultTableModel();
            dtm_con.addColumn("ID");
            dtm_con.addColumn("Tên");
            dtm_con.addColumn("Thông tin chung");
            dtm_con.addColumn("Thời gian bắt đầu");
            dtm_con.addColumn("Thời gian kết thúc");
            dtm_con.addColumn("Số lượng khách mời");
            dtm_con.addColumn("Chi tiết");
            List<Conference> ls_cf = cfDAO.findAll();
            for (Conference temp : ls_cf) {

                dtm_con.addRow(new Object[]{temp.getIdConference(), temp.getName(), temp.getGeneralInfo(), temp.getStartedtime(), temp.getEndedtime(), temp.getVisitors(), temp.getDetail()});
            }
            this.listConference.setModel(dtm_con);

            DefaultTableModel dtm_visitors = new DefaultTableModel();
            dtm_visitors.addColumn("Tên hội nghị");
            dtm_visitors.addColumn("Username");
            dtm_visitors.addColumn("Tên khách mời");
            dtm_visitors.addColumn("status");
            this.listVisitors.setModel(dtm_visitors);

            List<Place> ls_place = plDAO.findAll();
            String[] data = new String[ls_place.size()];
            for (int i = 0; i < ls_place.size(); i++) {
                data[i] = ls_place.get(i).getName();
            }
            DefaultComboBoxModel cbm = new DefaultComboBoxModel(data);
            this.placeComboBox.setModel(cbm);
            this.listConference.setModel(dtm_con);
        } else {
            JOptionPane.showMessageDialog(null, "Cập nhật nghị không thành công !!!");
        }
    }//GEN-LAST:event_updateButtonActionPerformed

    private void visitorsTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visitorsTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_visitorsTextFieldActionPerformed

    private void statisticButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statisticButtonActionPerformed
        // TODO add your handling code here:
        JFrameListUser j = new JFrameListUser(CurrentUser);
        j.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_statisticButtonActionPerformed

    private void addConferenceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addConferenceButtonActionPerformed
        // TODO add your handling code here:
        JFrameNewConference j = new JFrameNewConference(CurrentUser);
        j.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_addConferenceButtonActionPerformed

    private void addPlaceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPlaceButtonActionPerformed
        // TODO add your handling code here:
        JFrameNewPlace j = new JFrameNewPlace(CurrentUser);
        j.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_addPlaceButtonActionPerformed

    private void listConferenceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listConferenceMouseClicked
        // TODO add your handling code here:
        int id = Integer.parseInt(this.listConference.getValueAt(this.listConference.getSelectedRow(), 0).toString());
        System.out.println(id);
        Conference cf = cfDAO.find(id);
        Place pl = plDAO.find(cf.getPlace().getIdPlace());
        System.out.println(pl.getName());
        this.nameConferenceTextField.setText(cf.getName());
        this.generalInfoTextField.setText(cf.getGeneralInfo());
        this.startedTimeTextField.setText(cf.getStartedtime().toString());
        this.endedTimeTextField.setText(cf.getEndedtime().toString());
        this.placeComboBox.setSelectedIndex(pl.getIdPlace() - 1);
        this.visitorsTextField.setText(String.valueOf(cf.getVisitors()));
        this.detailTextField.setText(cf.getDetail());

        DefaultTableModel dtm_visitors = new DefaultTableModel();
        dtm_visitors.addColumn("Tên hội nghị");
        dtm_visitors.addColumn("Username");
        dtm_visitors.addColumn("Tên khách mời");
        dtm_visitors.addColumn("Trạng thái");

        List<Attendance> ls_at = atDAO.findAll();
        for (Attendance temp : ls_at) {
            Conference t1 = cfDAO.find(id);
            User u1 = usDAO.findByID(temp.getId().getIdUser());
            if (t1.getIdConference() == temp.getId().getIdConference()) {
                String status;
                if (temp.getStatusUser() == 1) {
                    status = "Đã tham gia";
                } else {
                    status = "Đang chờ duyệt...";
                }
                dtm_visitors.addRow(new Object[]{t1.getName(), u1.getUsername(), u1.getName(), status});
            }
        }
        this.listVisitors.setModel(dtm_visitors);
    }//GEN-LAST:event_listConferenceMouseClicked

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // TODO add your handling code here:
        Conference cf = cfDAO.find(Integer.parseInt(this.listConference.getValueAt(this.listConference.getSelectedRow(), 0).toString()));
        if (cfDAO.delete(cf)) {
            JOptionPane.showMessageDialog(null, "Delete conference successfully !!!");
            DefaultTableModel dtm_con = new DefaultTableModel();
            dtm_con.addColumn("ID");
            dtm_con.addColumn("Tên");
            dtm_con.addColumn("Thông tin chung");
            dtm_con.addColumn("Thời gian bắt đầu");
            dtm_con.addColumn("Thời gian kết thúc");
            dtm_con.addColumn("Số lượng khách mời");
            dtm_con.addColumn("Chi tiết");
            List<Conference> ls_cf = cfDAO.findAll();
            for (Conference temp : ls_cf) {

                dtm_con.addRow(new Object[]{temp.getIdConference(), temp.getName(), temp.getGeneralInfo(), temp.getStartedtime(), temp.getEndedtime(), temp.getVisitors(), temp.getDetail()});
            }
            this.listConference.setModel(dtm_con);

            DefaultTableModel dtm_visitors = new DefaultTableModel();
            dtm_visitors.addColumn("Tên hội nghị");
            dtm_visitors.addColumn("Username");
            dtm_visitors.addColumn("Tên khách mời");
            dtm_visitors.addColumn("status");
            this.listVisitors.setModel(dtm_visitors);

            List<Place> ls_place = plDAO.findAll();
            String[] data = new String[ls_place.size()];
            for (int i = 0; i < ls_place.size(); i++) {
                data[i] = ls_place.get(i).getName();
            }
            DefaultComboBoxModel cbm = new DefaultComboBoxModel(data);
            this.placeComboBox.setModel(cbm);
            this.nameConferenceTextField.setText("");
            this.generalInfoTextField.setText("");
            this.startedTimeTextField.setText("");
            this.endedTimeTextField.setText("");
            this.visitorsTextField.setText("");
            this.detailTextField.setText("");
        } else {
            JOptionPane.showMessageDialog(null, "Delete conference unsuccessfully !!!");
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void confirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmButtonActionPerformed
        // TODO add your handling code here:
        String username = this.listVisitors.getValueAt(this.listVisitors.getSelectedRow(), 1).toString();
        int id = Integer.parseInt(this.listConference.getValueAt(this.listConference.getSelectedRow(), 0).toString());
        User us = usDAO.find(username);
        System.out.println(id);
        System.out.println(us.getIdUser());
        AttendanceId ID = new AttendanceId(id, us.getIdUser());
        Attendance temp = atDAO.find(ID);
        temp.setStatusUser(1);
        if (atDAO.update(temp)) {
            JOptionPane.showMessageDialog(null, "Đã chấp nhận yêu cầu tham gia");
        } else {
            JOptionPane.showMessageDialog(null, "Chấp nhận không thành công");
        }
        DefaultTableModel dtm_visitors = new DefaultTableModel();
        dtm_visitors.addColumn("Tên hội nghị");
        dtm_visitors.addColumn("Username");
        dtm_visitors.addColumn("Tên khách mời");
        dtm_visitors.addColumn("Trạng thái");

        List<Attendance> ls_at = atDAO.findAll();
        for (Attendance i : ls_at) {
            Conference t1 = cfDAO.find(id);
            User u1 = usDAO.findByID(i.getId().getIdUser());
            if (t1.getIdConference() == i.getId().getIdConference()) {
                String status;
                if (i.getStatusUser() == 1) {
                    status = "Đã tham gia";
                } else {
                    status = "Đang chờ duyệt...";
                }
                dtm_visitors.addRow(new Object[]{t1.getName(), u1.getUsername(), u1.getName(), status});
            }
        }
        this.listVisitors.setModel(dtm_visitors);
    }//GEN-LAST:event_confirmButtonActionPerformed

    private void denyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_denyButtonActionPerformed
        // TODO add your handling code here:
        String username = this.listVisitors.getValueAt(this.listVisitors.getSelectedRow(), 1).toString();
        int id = Integer.parseInt(this.listConference.getValueAt(this.listConference.getSelectedRow(), 0).toString());
        User us = usDAO.find(username);
        AttendanceId ID = new AttendanceId(id, us.getIdUser());
        Attendance temp = atDAO.find(ID);
        temp.setStatusUser(1);
        if (atDAO.delete(temp)) {
            JOptionPane.showMessageDialog(null, "Đã từ chối yêu cầu tham gia");
        } else {
            JOptionPane.showMessageDialog(null, "Từ chối yêu cầu không thành công");
        }
        DefaultTableModel dtm_visitors = new DefaultTableModel();
        dtm_visitors.addColumn("Tên hội nghị");
        dtm_visitors.addColumn("Username");
        dtm_visitors.addColumn("Tên khách mời");
        dtm_visitors.addColumn("Trạng thái");

        List<Attendance> ls_at = atDAO.findAll();
        for (Attendance i : ls_at) {
            Conference t1 = cfDAO.find(id);
            User u1 = usDAO.findByID(i.getId().getIdUser());
            if (t1.getIdConference() == i.getId().getIdConference()) {
                String status;
                if (i.getStatusUser() == 1) {
                    status = "Đã tham gia";
                } else {
                    status = "Đang chờ duyệt...";
                }
                dtm_visitors.addRow(new Object[]{t1.getName(), u1.getUsername(), u1.getName(), status});
            }
        }
        this.listVisitors.setModel(dtm_visitors);
    }//GEN-LAST:event_denyButtonActionPerformed

    private void listVisitorsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listVisitorsMouseClicked
        // TODO add your handling code here:
        String status = this.listVisitors.getValueAt(this.listVisitors.getSelectedRow(), 3).toString();
        if (status == "Đã tham gia") {
            this.confirmButton.setEnabled(false);
        } else {
            System.out.println("Hello");
            this.confirmButton.setEnabled(true);
        }
    }//GEN-LAST:event_listVisitorsMouseClicked

    private void searchBarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchBarActionPerformed

    private void searchBarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchBarKeyReleased
        // TODO add your handling code here:
        String query = this.searchBar.getText();
        filter(query);
    }//GEN-LAST:event_searchBarKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameIndexAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameIndexAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameIndexAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameIndexAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameIndexAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addConferenceButton;
    private javax.swing.JButton addPlaceButton;
    private javax.swing.JPanel avatar;
    private javax.swing.JButton confirmButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton denyButton;
    private javax.swing.JScrollPane detailTextArea;
    private javax.swing.JTextArea detailTextField;
    private javax.swing.JButton editButton;
    private javax.swing.JTextField endedTimeTextField;
    private javax.swing.JTextField generalInfoTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable listConference;
    private javax.swing.JTable listVisitors;
    private javax.swing.JButton logoutButton;
    private javax.swing.JTextField nameConferenceTextField;
    private javax.swing.JPanel optionSpace;
    private javax.swing.JComboBox<String> placeComboBox;
    private javax.swing.JPanel playground;
    private javax.swing.JTextField searchBar;
    private javax.swing.JButton showConferenceButton;
    private javax.swing.JTextField startedTimeTextField;
    private javax.swing.JButton statisticButton;
    private javax.swing.JButton updateButton;
    private javax.swing.JTextField visitorsTextField;
    // End of variables declaration//GEN-END:variables

    private boolean checkAddConference(Conference current, Place pl, String temp1, String temp2) {
        List<Conference> ls_cf = cfDAO.findByPlace(pl);
        for (int i = 0; i < ls_cf.size(); i++) {
            if (ls_cf.get(i).getIdConference() == current.getIdConference()) {
                ls_cf.remove(i);
            }
        }
        if (!ls_cf.isEmpty()) {
            Date newStartedDay = null;
            Date newEndedDay = null;
            try {
                newStartedDay = newDateFormat.parse(temp1);
                newEndedDay = newDateFormat.parse(temp2);
            } catch (Exception e) {
                e.printStackTrace();
            }
            if (newStartedDay.compareTo(newEndedDay) >= 0) {
                return false;
            }
            for (Conference i : ls_cf) {
                if (i.getStatus() == 1) {
                    if (((newStartedDay.compareTo(i.getStartedtime())) >= 0 && (newStartedDay.compareTo(i.getEndedtime())) <= 0) || ((newEndedDay.compareTo(i.getStartedtime())) >= 0 && (newEndedDay.compareTo(i.getEndedtime())) <= 0)) {
                        return false;
                    }
                }
            }
        }
        return true;
    }

}
