package entities;
// Generated Jul 27, 2020, 9:35:57 AM by Hibernate Tools 4.3.1



/**
 * Attendance generated by hbm2java
 */
public class Attendance  implements java.io.Serializable {


     private AttendanceId id;
     private Conference conference;
     private User user;
     private Integer statusUser;

    public Attendance() {
    }

	
    public Attendance(AttendanceId id, Conference conference, User user) {
        this.id = id;
        this.conference = conference;
        this.user = user;
    }
    public Attendance(AttendanceId id, Conference conference, User user, Integer statusUser) {
       this.id = id;
       this.conference = conference;
       this.user = user;
       this.statusUser = statusUser;
    }
   
    public AttendanceId getId() {
        return this.id;
    }
    
    public void setId(AttendanceId id) {
        this.id = id;
    }
    public Conference getConference() {
        return this.conference;
    }
    
    public void setConference(Conference conference) {
        this.conference = conference;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Integer getStatusUser() {
        return this.statusUser;
    }
    
    public void setStatusUser(Integer statusUser) {
        this.statusUser = statusUser;
    }




}


