package entities;
// Generated Jul 27, 2020, 9:35:57 AM by Hibernate Tools 4.3.1



/**
 * AttendanceId generated by hbm2java
 */
public class AttendanceId  implements java.io.Serializable {


     private int idConference;
     private int idUser;

    public AttendanceId() {
    }

    public AttendanceId(int idConference, int idUser) {
       this.idConference = idConference;
       this.idUser = idUser;
    }
   
    public int getIdConference() {
        return this.idConference;
    }
    
    public void setIdConference(int idConference) {
        this.idConference = idConference;
    }
    public int getIdUser() {
        return this.idUser;
    }
    
    public void setIdUser(int idUser) {
        this.idUser = idUser;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AttendanceId) ) return false;
		 AttendanceId castOther = ( AttendanceId ) other; 
         
		 return (this.getIdConference()==castOther.getIdConference())
 && (this.getIdUser()==castOther.getIdUser());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdConference();
         result = 37 * result + this.getIdUser();
         return result;
   }   


}


