package entities;
// Generated Jul 27, 2020, 9:35:57 AM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Place generated by hbm2java
 */
public class Place implements java.io.Serializable {

    private int idPlace;
    private String name;
    private int capacity;
    private String address;
    private Set conferences = new HashSet(0);

    public Place() {
    }

    public Place(int idPlace, String name, int capacity) {
        this.idPlace = idPlace;
        this.name = name;
        this.capacity = capacity;
    }

    public Place(int idPlace, String name, int capacity, Set conferences) {
        this.idPlace = idPlace;
        this.name = name;
        this.capacity = capacity;
        this.conferences = conferences;
    }

    public int getIdPlace() {
        return this.idPlace;
    }

    public void setIdPlace(int idPlace) {
        this.idPlace = idPlace;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getAddress() {
        return this.address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public int getCapacity() {
        return this.capacity;
    }

    public void setCapacity(int capacity) {
        this.capacity = capacity;
    }

    public Set getConferences() {
        return this.conferences;
    }

    public void setConferences(Set conferences) {
        this.conferences = conferences;
    }

}
