package entities;
// Generated Jul 27, 2020, 9:35:57 AM by Hibernate Tools 4.3.1

import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.security.SecureRandom;
import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

    private int idUser;
    private String name;
    private String username;
    private String password;
    private String email;
    private int state;
    private Set attendances = new HashSet(0);

    public User() {
    }

    public User(int idUser) {
        this.idUser = idUser;
    }

    public User(int idUser, String name, String username, String password, String email, int state, Set attendances) {
        this.idUser = idUser;
        this.name = name;
        this.username = username;
        this.password = password;
        this.email = email;
        this.state = state;
        this.attendances = attendances;
    }

    public int getIdUser() {
        return this.idUser;
    }

    public void setIdUser(int idUser) {
        this.idUser = idUser;
    }


    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getUsername() {
        return this.username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public int getState() {
        return this.state;
    }

    public void setState(int state) {
        this.state = state;
    }

    public Set getAttendances() {
        return this.attendances;
    }

    public void setAttendances(Set attendances) {
        this.attendances = attendances;
    }


}
